server:
  port: 7000

security:
  basic:
    enabled: true
  user:
      name: agile # login username
      password: agile # login password
eureka:
  datacenter: paperless
  # 设置环境标识
  environment: dev
  server:
      # 关闭自我保护
      enable-self-preservation: false
      # 设置清理节点时间间隔（默认60*1000 单位毫秒）
      eviction-interval-timer-in-ms: 3000

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://agile:agile@127.0.0.1:7000/eureka


