server:
  port: 9002
  context-path: /

spring:
  application:
    name: backstage-service
  datasource:
    ####### spring boot 整合 druid start #######
      druid:
        url: jdbc:oracle:thin:@192.168.1.247:1521:bhps
        username: cmcc_sx
        password: abc123
        driver-class-name: oracle.jdbc.driver.OracleDriver
        # 初始化连接数大小
        initial-size: 2
        # 最小连接数
        min-idle: 2
        # 最大连接数
        max-active: 30
        web-stat-filter:
          enabled: true
        stat-view-servlet:
          login-username: druid
          login-password: druid
          enabled: true
        #配置获取连接等待超时的时间
        max-wait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filter: stat,wall,log4j
        # 合并多个DruidDataSource的监控数据
        use-global-data-source-stat: true
  ########################################################
  ###Redis (RedisConfiguration)
  ########################################################
#  redis:
#  # Redis数据库索引（默认为0）
#    database: 0
#    # Redis服务器地址
#    host: 192.168.1.95
#    # Redis服务器连接端口
#    port: 7379
#    pool:
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最小空闲连接
#      min-idle: 0
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#    # 连接超时时间（毫秒）
#    timeout: 1000
#    #password: 654321
    ####### spring boot 整合 druid end #######
eureka:
  # 设置环境标识
  environment: dev
  client:
    serviceUrl:
    ## http://admin:admin@localhost:8761/eureka
      defaultZone: http://agile:agile@localhost:7000/eureka
    # 开启健康检查（需要 spring-boot-starter-actuator）
    healthcheck:
          enabled: true
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${spring.cloud.client.ipAddress}:${server.port}}
    # 租期更新时间间隔（默认30毫秒）
    lease-renewal-interval-in-seconds: 10
    # 租期到期时间（默认90毫秒）
    lease-expiration-duration-in-seconds: 30
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl